[tools]
gradle = "8.12.1"
java = "corretto-21.0.6.7.1"

[tasks.test]
description = "全テストを実行"
run = ["gradle test --info"]

[tasks."test:single"]
description = "指定したテストクラスのみを実行"
# Example: mise run test:single --class ClassNameSearcher
run = 'gradle test --tests "com.example.{{option(name="class")}}" --info'

[tasks.auto-format]
description = "コードを自動フォーマット"
run = "gradle ktlintFormat"
